### ISSUE TITLE
Replying to multiple pages of messages

### ISSUE THREAD

**Issue by dancancro** [eladnava/batch-reply-for-gmail#3]
When I have many pages of messages and select all, the messages from only the current page are selected. Gmail then asks if I want to select all messages. So I do that. I can then choose to move all of them to a folder, or delete them.

If I click "Reply" it creates a message addressed only to the senders of the first page of messages.

Is it possible to reply to all messages or just one page-full of messages?

**Comment by eladnava** [comment]
Hi @dancancro and thanks for reporting the issue!

Currently it is not possible to support the "Select all X conversations in Y" feature that looks like this:
![screen shot 2016-04-27 at 11 56 24 pm](https://cloud.githubusercontent.com/assets/4394189/14867925/b043fa94-0cd3-11e6-9e74-a851c9371222.png)

This is because those e-mails are not actually loaded into the browser when you use that feature.

And if you perform an action to the entire folder, e.g. "Delete" or "Archive", Gmail will perform that action in its server-side without the client actually knowing which messages were affected.

Therefore, this Chrome extension won't be able to extract all of the sender e-mails from those thousands of selected e-mails, since they never make it to the browser.

However, if you don't have that many e-mails in the current folder, you can manually select all the e-mails in each page, and the extension will concatenate all of the selected e-mails' senders (from all the pages) into a single e-mail with you click **Reply**.

**Comment by eladnava** [comment]
Closing this as there doesn't seem to be any logical solution right now.
